#!/bin/bash
### BEGIN INIT INFO
# Provides: halley
# Required-Start: $local_fs $network
# Required-Stop: $local_fs
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: halley
# Description: halley the space invader (door watch) daemon
### END INIT INFO
# Haldor init script

su halley - /home/halley/halley/start.sh "$@"
